openapi: 3.0.1
info:
  title: PMWEBAPI
  description: |
    ## ABOUT PMWEBAPI
    ### PMWEBAPI
    Introduction to the Performance Metrics Web Application Programming Interface

    ### HTTP SYNOPSIS
    *  **GET /metrics**

    *  **GET /series/...**
      
    *  **GET /search/...**
      
    *  **GET /pmapi/...**

    ### C SYNOPSIS
    &nbsp;&nbsp;&nbsp;&nbsp;**\#include <[pcp/pmwebapi.h](https://github.com/performancecopilot/pcp/blob/master/src/include/pcp/pmwebapi.h)>**
    
    &nbsp;&nbsp;&nbsp;&nbsp;... assorted routines ...
    
    &nbsp;&nbsp;&nbsp;&nbsp;cc ... -lpcp_web -lpcp

    ### DESCRIPTION
    The PMWEBAPI is a collection of interfaces providing Performance Co-Pilot services for web applications. It consists of APIs for web applications querying and analysing both live and historical performance data, as well as APIs used by web servers.

    The usual HTTP URL-encoded optional parameter rules apply and PMWEBAPI REST requests always follow the convention:
    ```
    /api/endpoint ? parameter1 = value1 & parameter2 = value2
    ```

    Examples in all following sections use the [curl](https://man7.org/linux/man-pages/man1/curl.1.html)(1) command line utility with a local [pmproxy](https://pcp.io/man/man1/pmproxy.1.html)(1) server listening on port 44322 (default port). The [pmjson](https://pcp.io/man/man1/pmjson.1.html)(1) utility is used to neatly format any JSON output, as opposed to the compact (minimal whitespace) form provided by default. The examples in the scalable time series section use historical data recorded by the [pmlogger](https://pcp.io/man/man1/pmlogger.1.html)(1) service, in conjunction with a local [redis-server](https://man7.org/linux/man-pages/man1/redis-server.1.html)(1).
  version: ""
servers:
- url: http://localhost:44322/
tags:
- name: OPEN METRICS
  description: |
    Exporting of live performance metrics in an Open Metrics compatible format (as described at https://openmetrics.io and popularized by the https://prometheus.io project) is available.
- name: SCALABLE TIME SERIES
  description: |
    The fast, scalable time series query capabilities provided by the [pmseries](https://pcp.io/man/man1/pmseries.1.html)(1) command are also available through a REST API. These queries provide access to performance data (metric metadata and values) from multiple hosts simultaneously, and in a fashion suited to efficient retrieval by any number of web applications.

    All requests in this group can be accompanied by an optional *client* parameter. The value passed in the request will be sent back in the response - all responses will be in JSON object form in this case, with top level "client" and "result" fields.
- name: FULL TEXT SEARCH
  description: |
    The full text search capabilities provided by the [pmsearch](https://pcp.io/man/man1/pmsearch.1.html)(1) command are also available through a REST API. These queries provide access to an index over performance metric names, instances, instance domains and help text, suitable for a metric search engine, and in a fashion suited to efficient querying by any number of web applications.

    In order to use this functionality, the optional *RediSearch* module must be loaded in the **redis-server** at the time **pmproxy** is started, such that metrics, instances and help text it discovers can be automatically indexed.
- name: PMAPI HOST SERVICES
  description: |
    The live performance collection facilities available from [pmcd](https://pcp.io/man/man1/pmcd.1.html)(1) can also be accessed through a REST API.

    All requests are performed on the web server host by default, unless either a *hostspec* or *context* parameter is provided. *hostname* can be used in place of *hostspec*.

    Context identifiers are used as a persistent way to refer to PMAPI contexts across related web requests. These contexts expire after a configurable period of disuse, and are either explicitly allocated using the */pmapi/context* interface, or implicitly allocated using other interfaces.

    The timeout interval is configurable at context creation time, and as such the *polltime* parameter can be used anywhere the *hostspec* is specified. It sets the context timeout in terms of length of inactive time. The unit for the timeout value is seconds and the default is 5.

    To specify a specific existing context in any PMAPI web request, the endpoints can be accessed with either the *context* parameter or enbedded in the endpoint URL itself, such as **/pmapi/[number]/fetch**.
paths:
  /metrics:
    get:
      tags:
      - OPEN METRICS
      summary: Fetches current values and metadata 
      description: " `Get metrics` fetches current values and metadata for all metrics, or only metrics\
        \ indicated by a comma-separated list of names. For all numeric metrics with the given NAME prefixes, create an\
        \ Open Metrics (Prometheus) text export format giving their current value\
        \ and related metadata.\n\nThe response has plain text type rather than JSON\
        \ commonly used elsewhere in the REST API. This format can be injested by\
        \ many open source monitoring tools, including Prometheus and [pmdaopenmetrics](https://pcp.io/man/man1/pmdaopenmetrics.1.html)(1).\n\
        \nThe native PCP metric metadata (metric name, type, indom, semantics and\
        \ units) is first output for each metric with **# PCP** prefix. The metadata\
        \ reported is of the form described on [pmTypeStr](https://pcp.io/man/man3/pmtypestr.3.html)(3),\
        \ [pmInDomStr](https://pcp.io/man/man3/pmindomstr.3.html)(3), [pmSemStr](https://pcp.io/man/man3/pmsemstr.3.html)(3)\
        \ and [pmUnitsStr](https://pcp.io/man/man3/pmunitsstr.3.html)(3) respectively.\
        \ If the [pmUnitsStr](https://pcp.io/man/man3/pmunitsstr.3.html)(3) units\
        \ string is empty, then **none** is output. The units metadata string may\
        \ contain spaces and extends to the end of the line.\n\nPCP metric names are\
        \ mapped so that the **.** separators are exchanged with **\\_** (':' in back-compatibility\
        \ mode, where \"# PCP\" is the identifying line suffix). Both metric labels\
        \ and instances are represented as Prometheus labels, with external instance\
        \ names being quoted and the flattened PCP metric hierarchy being presented\
        \ with each value.\n```\n$ curl -s http://localhost:44322/metrics?names=proc.nprocs,kernel.pernode.cpu.intr,filesys.blocksize\n\
        \n# PCP5 proc.nprocs 3.8.99 u32 PM_INDOM_NULL instant none  \n# HELP proc_nprocs\
        \ instantaneous number of processes\n# TYPE proc_nprocs gauge\nproc_nprocs\
        \ {hostname=\"app1\"} 7\n\n# PCP5 kernel.pernode.cpu.intr 60.0.66 u64 60.19\
        \ counter millisec\n# HELP kernel_pernode_cpu_intr total interrupt CPU [...]\n\
        # TYPE kernel_pernode_cpu_intr counter\nkernel_pernode_cpu_intr{hostname=\"\
        app1\",instname=\"node0\"} 25603\n\n# PCP5 filesys.blocksize 60.5.9 u32 60.5\
        \ instant byte\n# HELP filesys_blocksize Size of each block on mounted file[...]\n\
        # TYPE filesys_blocksize gauge\nfilesys_blocksize{hostname=\"app1\",instname=\"\
        /dev/sda1\"} 4096\nfilesys_blocksize{hostname=\"app1\",instname=\"/dev/sda2\"\
        } 4096\n\n```\n"
      parameters:
      - name: names
        in: query
        description: Comma-separated list of metric names
        schema:
          type: string
      - name: times
        in: query
        description: Append sample times (milliseconds since epoch)
        schema:
          type: boolean
  /series/query:
    get:
      tags:
      - SCALABLE TIME SERIES
      summary: Performs a time series query
      description: |
        The query is in the format described in [pmseries](https://pcp.io/man/man1/pmseries.1.html)(1) and is passed to the server via either the *expr* parameter (HTTP GET) or via the message body (HTTP POST).

        When querying for time series matches only, no time window options are specified and matching series identifiers are returned in a JSON array.
        ```
        $ curl -s http://localhost:44322/series/query?expr=disk.dev.read* | pmjson
        ```
        When querying for time series values as well, a time window must be specified as part of the query string. The simplest form is to just request the most recent sample.
        ```
        $ curl -s http://localhost:44322/series/query?expr=disk.dev.read*[samples:1] | pmjson
        ```
        **References:** [pmSeriesQuery](https://man7.org/linux/man-pages/man3/pmSeriesQuery.3.html)(3)
      operationId: get/series/query
      parameters:
      - name: expr
        in: query
        description: Query string in pmseries (1) format
        schema:
          type: string
      - name: client
        in: query
        description: Request identifier sent back with response
        schema:
          type: string
      responses:
        200:
          description: successful operation
          content:
            pmjson:
              schema:
                anyOf:
                - $ref: '#/components/schemas/response1'
                - $ref: '#/components/schemas/response2'

                
  /series/values:
    get:
      tags:
      - SCALABLE TIME SERIES
      summary: Performs values retrievals for one or more time series identifiers
      description: |
        The JSON response contains the same information as the **pmseries - q /-- query** option using any of the time window parameters described on [pmseries](https://pcp.io/man/man1/pmseries.1.html)(1). If no time window parameters are specified, the single most recent value observed is retrieved.
        ```
        $ curl -s http://localhost:44322/series/values?series=605fc77742cd0317597291329561ac4e50c0dd12 | pmjson
        ```
        **References:** [pmSeriesValues](https://man7.org/linux/man-pages/man3/pmSeriesValues.3.html)(3)

      operationId: get/series/values
      parameters:
      - name: series
        in: query
        description: Comma-separated list of series identifiers
        schema:
          type: string
      - name: client
        in: query
        description: Request identifier sent back with response
        schema:
          type: string
      - name: samples
        in: query
        description: Count of samples to return
        schema:
          type: number
      - name: interval
        in: query
        description: Time between successive samples
        schema:
          type: string
      - name: start
        in: query
        description: Sample window start time
        schema:
          type: string
      - name: finish
        in: query
        description: Sample window end time
        schema:
          type: string
      - name: offset
        in: query
        description: Sample window offset
        schema:
          type: string
      - name: align
        in: query
        description: Sample time alignment
        schema:
          type: string
      - name: zone
        in: query
        description: Time window timezone
        schema:
          type: string
      responses:
        200:
          description: successful operation
          content:
            pmjson:
              schema:
                type: array
                example:
                - series: 605fc77742cd0317597291329561ac4e50c0dd12
                  timestamp: 1.3176330229599592E12
                  value: "71660"
                items:
                  type: object
                  properties:
                    series:
                      type: string
                    timestamp:
                      type: integer
                    value:
                      type: string
  /series/descs:
    get:
      tags:
      - SCALABLE TIME SERIES
      summary: Performs a descriptor lookup for one or more time series identifiers
      description: |
        The JSON response contains the same information as the **pmseries - d /-- desc** option.
        ```
        $ curl -s http://localhost:44322/series/descs?series=605fc77742cd0317597291329561ac4e50c0dd12 | pmjson
        ```
        **References:** [pmSeriesDescs](https://man7.org/linux/man-pages/man3/pmSeriesDescs.3.html)(3)
      operationId: get/series/descs
      parameters:
      - name: series
        in: query
        description: Comma-separated list of series identifiers
        schema:
          type: string
      - name: client
        in: query
        description: Request identifier sent back with response
        schema:
          type: string
      responses:
        200:
          description: successful operation
          content:
            pmjson:
              schema:
                type: object
                properties:
                  series:
                    type: string
                  source:
                    type: integer
                  pmid:
                    type: string
                  indom:
                    type: string
                  semantics:
                    type: integer
                  type:
                    type: string
                  units:
                    type: string
                example:
                - series: 605fc77742cd0317597291329561ac4e50c0dd12
                  source: f5ca7481da8c038325d15612bb1c6473ce1ef16f
                  pmid: 60.0.4
                  indom: 60.1
                  semantics: counter
                  type: u32
                  units: count
  /series/labels:
    get:
      tags:
      - SCALABLE TIME SERIES
      summary: Performs a label set lookup 
      description: |
        This command operates in one of three modes.

        It can perform a label set lookup for one or more time series identifiers, when given the series parameter. The JSON response for this mode contains the same information as the **pmseries - I /-- labels** option.
        ```
        $ curl -s http://localhost:44322/series/labels?series=605fc77742cd0317597291329561ac4e50c0dd12 | pmjson
        ```
        It can produce a list of all known label names, in the absense of name , names or series parameters. The JSON responses for this mode contains the same information as the **pmseries - l /-- labels** option.        
        ```
        $ curl -s http://localhost:44322/series/labels | pmjson
        ```
        It can produce a list of all known label values for a given label name or names . The JSON response for this mode contains the same information as the **pmseries - v /-- values** option.
        ```
        $ curl -s http://localhost:44322/series/labels?names=hostname,domainname | pmjson
        ```
        **References:** [pmSeriesLabels](https://man7.org/linux/man-pages/man3/pmSeriesLabels.3.html)(3), [pmSeriesLabelValues](https://man7.org/linux/man-pages/man3/pmSeriesLabelValues.3.html)(3)
      operationId: get/series/labels
      parameters:
      - name: series
        in: query
        description: Comma-separated list of series identifiers
        schema:
          type: string
      - name: match
        in: query
        description: Glob pattern string to match on all labels
        schema:
          type: string
      - name: name
        in: query
        description: Find all known label values for given name
        schema:
          type: string
      - name: names
        in: query
        description: Comma-separated list of label names
        schema:
          type: string
      - name: client
        in: query
        description: Request identifier sent back with response
        schema:
          type: string
      responses:
        200:
          description: successful operation
          content:
            pmjson:
              schema:
                anyOf:
                - $ref: '#/components/schemas/response3'
                - $ref: '#/components/schemas/response4'
                - $ref: '#/components/schemas/response5'
                
  /series/metrics:
    get:
      tags:
      - SCALABLE TIME SERIES
      summary: Performs a metric name lookup for one or more time series identifiers
      description: |
        The JSON response contains the same information as the **pmseries - m /-- metrics** option.
        ```
        $ curl -s http://localhost:44322/series/metrics?series=605fc77742cd0317597291329561ac4e50c0dd12 | pmjson
        ```
        Alternatively, with no *series* argument, this request will return the list of all known metric names.
        ```
        $ curl -s http://localhost:44322/series/metrics | pmjson
        ```
        **References:** [pmSeriesMetrics](https://man7.org/linux/man-pages/man3/pmSeriesMetrics.3.html)(3)
      operationId: get/series/metrics
      parameters:
      - name: series
        in: query
        description: Comma-separated list of series identifiers
        schema:
          type: string
      - name: match
        in: query
        description: Glob pattern string to match on all names
        schema:
          type: string
      - name: client
        in: query
        description: Request identifier sent back with response
        schema:
          type: string
      responses:
        200:
          description: successful operation
          content:
            pmjson:
              schema:
                anyOf:
                - $ref: '#/components/schemas/response6'
                - $ref: '#/components/schemas/response7'
                
  /series/sources:
    get:
      tags:
      - SCALABLE TIME SERIES
      summary: Performs a lookup for one or more time series sources
      description: |
        It returns an array of all PMAPI context names used to access the time series from that
        source.The JSON response contains the same information as the **pmseries - S /-- source** option.
        ```
        $ curl -s http://localhost:44322/series/sources?source=2cd6a38f9339f2dd1f0b4775bda89a9e7244def6 | pmjson
        ```
        **References:** [pmSeriesSources](https://man7.org/linux/man-pages/man3/pmSeriesSources.3.html)(3)
      operationId: get/series/sources
      parameters:
      - name: series
        in: query
        description: Comma-separated list of series identifiers
        schema:
          type: string
      - name: match
        in: query
        description: Glob pattern string to match on all names
        schema:
          type: string
      - name: client
        in: query
        description: Request identifier sent back with response
        schema:
          type: string
      responses:
        200:
          description: successful operation
          content:
            pmjson:
              schema:
                type: array
                example:
                - source: 2cd6a38f9339f2dd1f0b4775bda89a9e7244def6
                  context:
                  - /var/log/pcp/pmlogger/acme
                  - www.acme.com
                items:
                  type: object
                  properties:
                    source:
                      type: string
                    context:
                      type: array
                      items:
                        type: string
  /series/instances:
    get:
      tags:
      - SCALABLE TIME SERIES
      summary: Provides instance identifiers and names for one or more time series
        identifiers
      description: |
        The JSON response contains the same information as the **pmseries - i /-- instance** option.
        ```
        $ curl -s http://localhost:44322/series/instances?series=605fc77742cd0317597291329561ac4e50c0dd12 | pmjson
        ```
        Alternatively, with no *series* argument, this request will return the list of all known instance names.
        ```
        $ curl -s http://localhost:44322/series/instances | pmjson
        ```
        **References:** [pmSeriesInstances](https://man7.org/linux/man-pages/man3/pmSeriesInstances.3.html)(3)
      operationId: get/series/instances
      parameters:
      - name: series
        in: query
        description: Comma-separated list of series identifiers
        schema:
          type: string
      - name: match
        in: query
        description: Glob pattern string to match on all names
        schema:
          type: string
      - name: client
        in: query
        description: Request identifier sent back with response
        schema:
          type: string
      responses:
        200:
          description: successful operation
          content:
            pmjson:
              schema:
                anyOf:
                - $ref: '#/components/schemas/response8'
                - $ref: '#/components/schemas/response9'
                
  /series/load:
    get:
      tags:
      - SCALABLE TIME SERIES
      summary: Load time series performance data
      description: |
        It loads time series performance data from the specified source into the
        **redis-server** cache. This request is equivalent to the **pmseries - l /-- load** option.
        ```
        $ curl -s http://localhost:44322/series/load&expr={source.name:"/var/log/pcp/pmlogger/acme"}
        ```
        **References:** [pmSeriesLoad](https://man7.org/linux/man-pages/man3/pmSeriesLoad.3.html)(3)
      operationId: get/series/load
      parameters:
      - name: expr
        in: query
        description: Source load string in pmseries (1) format
        schema:
          type: string
      - name: client
        in: query
        description: Request identifier sent back with response
        schema:
          type: string
      responses:
        200:
          description: successful operation
          content:
            pmjson:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                example:
                  success: true

  /search/text:
    get:
      tags:
      - FULL TEXT SEARCH
      summary: Performs a text search query
      description: | 
        It performs a text search query across metrics and instance domains - all forms of names and help texts.
        
        The mandatory search string is further described in [pmsearch](https://pcp.io/man/man1/pmsearch.1.html)(1) and is passed to the server via the *query* parameter (HTTP GET).
        ```
        $ curl -s http://localhost:44322/search/text?query=halt | pmjson
        ```
        The available search entity *types* are *metric*, *indom* and *instance*. Query parameters *highlight* and *field* take *name*, *oneline* and *helptext*.

        Query parameter *return* takes *name*, *type*, *oneline*, *helptext*, *indom*. There is typically both a name and help text associated with metrics. Contents of these are then matched 
        against *query*. An instance domain has help text and a numeric identifier, while instances have a name only (which can be searched).
        
        **Reference:** [pmSearchTextQuery](https://man7.org/linux/man-pages/man3/pmSearchTextQuery.3.html)(3)
      operationID: get/search/text
      parameters:
      - name: query
        in: query
        description: Query string in pmsearch (1) format
        schema:
          type: string
      - name: highlight
        in: query
        description: Include matching markup in response fields
        schema:
          type: fields
      - name: offset
        in: query
        description: Result offset cursor for pagination
        schema:
          type: number
      - name: limit
        in: query
        description: Maximum results to include in response
        schema:
          type: number
      - name: field
        in: query
        description: Queried fields (defaults to all)
        schema:
          type: fields
      - name: return
        in: query
        description: Fields to actually return (defaults to all)
        schema:
          type: fields
      - name: type
        in: query
        description: Entity types to filter (defaults to all)
        schema:
          type: types
      responses:
        200:
          description: successful operation
          content:
            pmjson:
              schema:
                type: object
                properties:
                  total:
                    type: number
                  offset:
                    type: number
                  limit:
                    type: number
                  elapsed:
                    type: number
                  results:
                    type: array
                    items:
                      type: object
                      properties:
                        name:
                          type: string
                        type:
                          type: string
                        indom:
                          type: string
                        oneline:
                          type: string
                        helptext:
                          type: string
                        
                example:
                  total : 2
                  offset: 0
                  limit: 10
                  elapsed: 0.000504
                  results:
                    - name: kvm.halt_exits
                      type: metric
                      indom: 95.0.4
                      oneline: Number of guest exits due to halt calls.
                      helptext: This type of exit is usually seen when a guest is idle.
                    - name: kvm.halt_wakeup
                      type: metric
                      indom: 95.0.6
                      oneline: Number of wakeups from a halt.
                    
  /search/suggest:
    get:
      tags:
      - FULL TEXT SEARCH
      summary: Provides search query suggestions, that is, metric and instance names
      description: | 
        The mandatory search string is further described in [pmsearch](https://pcp.io/man/man1/pmsearch.1.html)(1) and is passed to the server via the *query* parameter (HTTP GET).
        ```
        $ curl -s http://localhost:44322/search/suggest?query=disk&limit=4 | pmjson
        ```
        **Reference:** [pmSearchTextSuggest](https://man7.org/linux/man-pages/man3/pmSearchTextSuggest.3.html)(3)
      operationID: get/search/suggest
      parameters:
      - name: query
        in: query
        description: Search query for search engine
        schema:
          type: string
      - name: limit
        in: query
        description: Max results to include in response
        schema:
          type: number
      responses:
        200:
          description: successful operation
          content:
            pmjson:
              schema:
                type: array
                items:
                  type: string
                example:
                - disk.all.avactive
                - disk.all.aveq
                - disk.all.blkread
                - disk.all.blktotal
  
  /search/indom:
    get:
      tags:
      - FULL TEXT SEARCH
      summary: Provides all entities related to indom
      description: | 
        It provides all entities (instances, metrics) related to indom, including itself, that is passed to the server via the *query* parameter.

        **Reference:** [pmSearchTextInDom](https://man7.org/linux/man-pages/man3/pmSearchTextInDom.3.html)(3)
      operationID: get/search/indom
      parameters:
      - name: query
        in: query
        description: Search indom for search engine
        schema:
          type: string
      - name: offset
        in: query
        description: Result offset cursor for pagination
        schema:
          type: number
      - name: limit
        in: query
        description: M results to include in response
        schema:
          type: number

  /search/info:
    get:
      tags:
      - FULL TEXT SEARCH
      summary: Provides metrics relating to operation
      description: | 
        It provides metrics relating to operation of the search engine, in particular showing document and text record counts.
        ```
        $ curl -s http://localhost:44322/search/info | pmjson
        ```
        **Reference:** [pmSearchInfo](https://man7.org/linux/man-pages/man3/pmSearchInfo.3.html)(3)
      operationID: get/search/info
      responses:
        200:
          description: successful operation
          content:
            pmjson:
              schema:
                type: object
                properties:
                  docs:
                    type: number
                  terms:
                    type: number
                  records:
                    type: number
                  records_per_doc_avg:
                    type: number
                  bytes_per_record_avg:
                    type: number
                  inverted_sz_mb:
                    type: number
                  inverted_cap_mb:
                    type: number
                  inverted_cap_ovh:
                    type: number
                  skip_index_size_mb:
                    type: number
                  score_index_size_mb:
                    type: number
                  offsets_per_term_avg:
                    type: number
                  offset_bits_per_record_avg:
                    type: number
                example:
                  docs: 1589
                  terms: 3855
                  records: 116831
                  records_per_doc_avg: 73.52
                  bytes_per_record_avg: 6.36
                  inverted_sz_mb: 0.71
                  inverted_cap_mb: 0.00
                  inverted_cap_ovh: 0.00
                  skip_index_size_mb: 0.00
                  score_index_size_mb: 0.00
                  offsets_per_term_avg: 9.41
                  offset_bits_per_record_avg: 8.00
    























components:
  schemas:
    response1:
      title: Without Time Window
      type: array
      items:
        type: string
      example:
        - 9d8c7fb51ce160eb82e3669aac74ba675dfa8900
        - ddff1bfe286a3b18cebcbadc1678a68a964fbe9d
        - 605fc77742cd0317597291329561ac4e50c0dd12

    response2:
      title: With Time Window
      type: array
      items:
        type: object
        properties:
          series:
            type: string
          instance:
            type: string
          timestamp:
            type: integer
          value:
            type: string
      example:
        - series: 9d8c7fb51ce160eb82e3669aac74ba675dfa8900
          instance: c3795d8b757506a2901c6b08b489ba56cae7f0d4
          timestamp: 1.5474836462147431E9
          value: 12499
        - series: ddff1bfe286a3b18cebcbadc1678a68a964fbe9d
          instance: 6b08b489ba56cae7f0d4c3795d8b757506a2901c
          timestamp: 1.5474857017431219E9
          value: 1118623
        - series: 605fc77742cd0317597291329561ac4e50c0dd12
          instance: c3795d8b757506a2901c6b08b489ba56cae7f0d4
          timestamp: 1.5474836462147431E9
          value: 71661

    response3:
      title: With series parameter
      type: object
      properties:
        series:
          type: string
        labels:
          type: object
          properties:
            agent:
              type: string
            domainname:
              type: string
            groupid:
              type: number
            hostname:
              type: string
            latitude:
              type: number
            longitude:
              type: number
            machineid:
              type: string
            platform:
              type: string
            userid:
              type: number
      example:
        - series: 605fc77742cd0317597291329561ac4e50c0dd12
          labels:
            agent: linux
            domainname: acme.com
            groupid: 1000
            hostname: www.acme.com
            latitude: -25.28496
            longitude: 152.87886
            machineid: 295b16e3b6074cc8bdbda8bf96f6930a
            platform: dev
            userid: 1000
                
    response4:
      title: Without any parameter
      type: array
      items:
        type: string
      example:
        - agent
        - appversion
        - domainname
        - groupid
        - hostname
        - jobid
        - latitude
        - longitude
        - machineid
        - platform
        - userid
                
    response5:
      title: With name/names parameter
      type: object
      properties:
        hostname:
          type: array
          items:
            type: string
        domainname:
          type: array
          items:
            type: string
      example:
        hostname:
          - app
          - nas
        domainname:
          - acme.com
        
    response6:
      title: With series parameter
      type: array
      items:
        type: object
        properties:
          series:
            type: string
          name:
            type: string
      example:
        - series: 605fc77742cd0317597291329561ac4e50c0dd12
          name: disk.dev.read_bytes
                
    response7:
      title: Without series parameter
      type: array
      items:
        type: string
      example:
        - disk.dev.read
        - disk.dev.read_bytes
        - disk.dev.read_merge
        - kernel.all.load
        - kernel.all.pswitch

    response8:
      title: With series parameter
      type: array
      items:
        type: object
        properties:
          series:
            type: string
          source:
            type: string
          instance:
            type: string
          id:
            type: number
          name:
            type: string
      example:
        - series: 605fc77742cd0317597291329561ac4e50c0dd12
          source: 97261ac7742cd4e50c0d03175913295d12605fc7
          instance: c3795d8b757506a2901c6b08b489ba56cae7f0d4
          id: 1
          name: sda
        - series: 605fc77742cd0317597291329561ac4e50c0dd12
          source: 97261ac7742cd4e50c0d03175913295d12605fc7
          instance: 57506a2901c6b08b489ba56cae7f0d4c3795d8b7
          id: 2
          name: sdb

    response9:
      title: Without series parameter
      type: array
      items:
        type: string
      example:
        - 1 minute
        - 5 minute
        - 15 minute
        - cpu0
        - cpu1
        - cpu2
        - cpu3
        - node0
        - node1
        - sda
        - sdb

